name: Build

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: wasabeef/import-asdf-tool-versions-action@main
        id: asdf
        with:
          path: .tool-versions
      - name: Echo asdf
        run: |
          echo "Flutter is ${{ steps.asdf.outputs.flutter }}"
          echo "Dart is ${{ steps.asdf.outputs.dart }}"
          echo "Node.js is ${{ steps.asdf.outputs.nodejs }}"
          echo "Gradle is ${{ steps.asdf.outputs.gradle }}"
          echo "Java is ${{ steps.asdf.outputs.java }}"
          echo "Kotlin is ${{ steps.asdf.outputs.kotlin }}"
