name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like vX.Y.Z

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create a release and push tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build for release
        run: bun run build

      - name: Commit and push dist files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f dist/ # Force add dist, in case it's in .gitignore in some branches
          # Commit only if there are changes in dist/
          if ! git diff --cached --quiet dist/; then
            git commit -m "build: add dist files for release ${{ github.ref_name }}"
          else
            echo "No changes in dist/ to commit."
          fi
          # Re-tag the commit that includes the build artifacts
          git tag -d ${{ github.ref_name }}
          git push origin :refs/tags/${{ github.ref_name }} # Delete remote tag first
          git tag ${{ github.ref_name }} # Create new tag locally
          git push --force origin ${{ github.ref_name }} # Force push the new tag

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }} # Tags like v1.0.0-beta are pre-releases
          # You can customize the body further if needed.
          # The body will be auto-generated by default.
